# Generated by Django 6.0.6 on 2026-08-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('VIRAL', 'Viral'), ('BACTERIAL', 'Bacterial'), ('FUNGAL', 'Fungal'), ('PARASITIC', 'Parasitic'), ('NUTRITIONAL', 'Nutritional'), ('BEHAVIORAL', 'Behavioral'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('prevention', models.TextField()),
                ('emergency_signs', models.TextField(blank=True)),
                ('is_common', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.diseaseinfo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='chatbot.diseaseinfo')),
            ],
            options={
                'unique_together': {('disease', 'keyword')},
            },
        ),
    ]
