# Generated by Django 6.1 on 2026-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seed_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='refund',
            name='deduction_percentage',
            field=models.IntegerField(default=10),
        ),
    ]
