# Generated by Django 6.1 on 2026-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='medical_suggestion',
            field=models.TextField(blank=True),
        ),
    ]
