# Generated by Django 6.1 on 2026-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_medicalhistory_medical_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medicines',
            field=models.TextField(blank=True),
        ),
    ]
