# Generated by Django 6.1 on 2026-09-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
